apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: test-filter
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://sfbrdevhelmweacr.azurecr.io/wasm-benchmark:regex
