[package]
name = "wasm-rust-filter"
version = "0.1.0"
edition = "2021"

[lib]
name = "plugin"
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.0"
log = "0.4"
primes = "0.3.0"
redis = "0.21.5"